# docker-compose file to run Joplin Server
# along with a PostgreSQL server.
#
# Update the following fields in the stanza below:
#
# POSTGRES_USER
# POSTGRES_PASSWORD
# APP_BASE_URL
#
# APP_BASE_URL: This is the base public URL where the service will be running.
# If Joplin Server needs to be accessible over the internet, configure APP_BASE_URL as follows: https://example.com/joplin. 
# If Joplin Server does not need to be accessible over the internet, set the the APP_BASE_URL to your server's hostname. 
#     For Example: http://[hostname]:22300. The base URL can include the port.
# APP_PORT: The local port on which the Docker container will listen. 
#	- This would typically be mapped to port to 443 (TLS) with a reverse proxy.
#	- If Joplin Server does not need to be accessible over the internet, the port can be mapped to 22300.


services:
  db:
    image: postgres:16.2-alpine3.19
    volumes:
      - ${DBVOLDIR}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    networks:
      - joplin

  app:
    image: joplin:2.14.20
    depends_on:
      - db
    #ports:
    #  - "22300:22300"
    restart: unless-stopped
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=MyTraefikNet"
      - "traefik.http.routers.joplincontainer.rule=Host(`${JOPLIN_FQDN}`)"
      #- "traefik.http.routers.joplincontainer.entrypoints=websecure"
      - "traefik.http.routers.joplincontainer.entrypoints=joplin"
      #- "traefik.http.routers.joplincontainer.tls=true"
      #- "traefik.http.routers.joplincontainer.tls.certresolver=mytlschallenge"
      #- "traefik.http.routers.joplincontainer.middlewares=security@file"
      - "traefik.http.routers.joplincontainer.service=myjoplinservice"
      - "traefik.http.services.myjoplinservice.loadbalancer.server.port=22300"
      - "traefik.http.services.myjoplinservice.loadbalancer.server.scheme=http"
    networks:
      - default
      - joplin

networks:
  default:
    external:
      name: MyTraefikNet

  joplin:
    internal: true
    name: MyJoplinNet
