# Docker Compose file to run Joplin Server along with a PostgreSQL server.
# Local dev test environment without traefik.
# Use .env.local for configuration.
# docker compose -f docker-compose-local.yml --env-file .env.local up -d
#
#    Copyright (C) 2026 - D4void
#    Licensed under the MIT License. See LICENSE file in the project root for details.

services:
  joplin_db:
    image: postgres:${POSTGRES_TAG}
    container_name: "MyJoplinPostgres"
    shm_size: 256M
    volumes:
      - joplin_db_data:/var/lib/postgresql/data
      - joplin_db_backup:/backup
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}     
    networks:
      - joplinnet

  joplin_app:
    image: d4void/joplin:${JOPLIN_TAG}
    container_name: "MyJoplinApp"
    ports:
      - "${JOPLIN_PORT}:${JOPLIN_PORT}"
    depends_on:
      - joplin_db
    restart: unless-stopped
    environment:
      - APP_PORT=${JOPLIN_PORT}
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=pg
      - POSTGRES_HOST=joplin_db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - MAILER_ENABLED=${MAILER_ENABLED}
      - MAILER_HOST=${MAILER_HOST}
      - MAILER_PORT=${MAILER_PORT}
      - MAILER_SECURITY=${MAILER_SECURITY}
      - MAILER_AUTH_USER=${MAILER_AUTH_USER}
      - MAILER_AUTH_PASSWORD=${MAILER_AUTH_PASSWORD}
      - MAILER_NOREPLY_NAME=${MAILER_NOREPLY_NAME}
      - MAILER_NOREPLY_EMAIL=${MAILER_NOREPLY_EMAIL}
    networks:
      - default
      - joplinnet


volumes:
  joplin_db_data:
    driver: local
    driver_opts:
      type: none
      device: ${DB_VOL}
      o: bind
  joplin_db_backup:
    driver: local
    driver_opts:
      type: none
      device: ${DB_BACKUP_VOL}
      o: bind


networks:
  joplinnet:
    internal: true
    name: MyJoplinNet
